/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa_2018_09_07_listaproductos;

import java.text.DecimalFormat;
import java.util.Random;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aa501
 */
public class jframePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form jframePrincipal
     */
    public jframePrincipal() {
        initComponents();
        
        jTableProductos.setShowGrid(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSpinProducto = new javax.swing.JSpinner();
        jbutaleatorios = new javax.swing.JButton();
        jbutcalcular = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabPromedio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripcion", "Costo", "% Utilidad", "% Descuento", "% Impuesto", "%Utilidad", "%Descuento", "%Impuesto", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableProductos);
        if (jTableProductos.getColumnModel().getColumnCount() > 0) {
            jTableProductos.getColumnModel().getColumn(0).setPreferredWidth(150);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Cuantos Productos:");

        jSpinProducto.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinProductoStateChanged(evt);
            }
        });

        jbutaleatorios.setText("Aleatorios");
        jbutaleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutaleatoriosActionPerformed(evt);
            }
        });

        jbutcalcular.setText("Calcular");
        jbutcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutcalcularActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Precio promedio:");

        jLabPromedio.setBackground(new java.awt.Color(102, 255, 255));
        jLabPromedio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabPromedio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabPromedio.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jbutaleatorios)
                        .addGap(18, 18, 18)
                        .addComponent(jbutcalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jSpinProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbutaleatorios)
                    .addComponent(jbutcalcular))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbutaleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutaleatoriosActionPerformed
        // TODO add your handling code here:
        Random azar = new Random();
        
        String [] desc = {"Chicles","Coca-Cola","Manteconcha","Leche","Pan Bimbo",
                          "Chocolate", "Sabritas", "Maruchan"};
    
        for(int r = 0; r < jTableProductos.getRowCount(); r++)
        {
            jTableProductos.setValueAt(desc[azar.nextInt(desc.length)], r, 0); //Descripción
            jTableProductos.setValueAt(5+azar.nextInt(95), r, 1); //Costo
            jTableProductos.setValueAt(5+azar.nextInt(25), r, 2); //%Utilidad
            jTableProductos.setValueAt(azar.nextInt(16), r, 3); //%Descuento
            jTableProductos.setValueAt(azar.nextInt(21), r, 4); //%Impuesto
        }
    }//GEN-LAST:event_jbutaleatoriosActionPerformed

    private void jSpinProductoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinProductoStateChanged
        // TODO add your handling code here:
        //Extraemos el modelo de datos del jTable-------------------------------
        DefaultTableModel modelo = (DefaultTableModel)jTableProductos.getModel();
        
        int renglones = Integer.parseInt(jSpinProducto.getValue().toString());
        modelo.setRowCount(renglones);
    }//GEN-LAST:event_jSpinProductoStateChanged

    private void jbutcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutcalcularActionPerformed
        // TODO add your handling code here:
        Producto equis = new Producto();
        
        DecimalFormat f = new DecimalFormat("###,###.00");
        double total = 0;
        for(int r = 0; r < jTableProductos.getRowCount();r++)
        {
            equis.setDescripcion(jTableProductos.getValueAt(r, 0)+"");
            equis.setCosto(Double.parseDouble(jTableProductos.getValueAt(r, 1)+""));
            equis.setMargenUtilidad(Double.parseDouble(jTableProductos.getValueAt(r, 2)+""));
            equis.setPorcentajeDescuento(Double.parseDouble(jTableProductos.getValueAt(r, 3)+""));
            equis.setPorcentajeImpuesto(Double.parseDouble(jTableProductos.getValueAt(r, 4)+""));
            
            jTableProductos.setValueAt(f.format(equis.importeUtilidad()),r,5);
            jTableProductos.setValueAt(f.format(equis.importeDescuento()),r,6);
            jTableProductos.setValueAt(f.format(equis.importeImpuesto()),r,7);
            jTableProductos.setValueAt(f.format(equis.precio()),r,8);
            
            total += equis.precio();
        }
        
        double promPrecio = total / jTableProductos.getRowCount();
        jLabPromedio.setText(f.format(promPrecio));
    }//GEN-LAST:event_jbutcalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabPromedio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinProducto;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JButton jbutaleatorios;
    private javax.swing.JButton jbutcalcular;
    // End of variables declaration//GEN-END:variables
}
